# Generated by Django 6.1.1 on 2026-10-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'پوشاک'), ('hygiene', 'بهداشتی'), ('jewelry', 'طلا و جواهرات'), ('cosmetics', 'لوازم آرایشی')], default='clothing', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
    ]
